"DynamicLoaderConfig" { 
"so_names" : [
"srrg2_core/lib/libsrrg2_boss_library.so",
"srrg2_core/lib/libsrrg2_config_library.so",
"srrg2_core/lib/libsrrg2_configurable_shell_library.so",
"srrg2_core/lib/libsrrg2_data_structures_library.so",
"srrg2_core/lib/libsrrg2_image_library.so",
"srrg2_core/lib/libsrrg2_matchable_library.so",
"srrg2_core/lib/libsrrg2_messages_library.so",
"srrg2_core/lib/libsrrg2_point_cloud_library.so",
"srrg2_core/lib/libsrrg2_property_library.so",
"srrg2_core/lib/libsrrg2_system_utils_library.so",
"srrg2_core/lib/libsrrg2_viewer_core_library.so",
"srrg2_core/lib/libsrrg2_viewer_library.so",
"srrg2_core_ros/lib/libsrrg2_converters_library.so",
"srrg2_core_ros/lib/libsrrg2_messages_ros_library.so",
"srrg2_kd_nicp/lib/libsrrg2_kd_slam_library.so",
"srrg2_navigation_2d/lib/libsrrg2_navigation_2d_library.so",
"srrg2_proslam/lib/libsrrg2_proslam_mapping_library.so",
"srrg2_proslam/lib/libsrrg2_proslam_registration_library.so",
"srrg2_proslam/lib/libsrrg2_proslam_sensor_processing_library.so",
"srrg2_proslam/lib/libsrrg2_proslam_tracking_library.so",
"srrg2_qgl_viewport/lib/libsrrg2_qgl_viewport_library.so",
"srrg2_slam_interfaces/lib/libsrrg2_slam_interfaces_library.so",
"srrg2_solver/lib/libsrrg2_solver_calib_library.so",
"srrg2_solver/lib/libsrrg2_solver_core_library.so",
"srrg2_solver/lib/libsrrg2_solver_factor_graph_utils_library.so",
"srrg2_solver/lib/libsrrg2_solver_incremental_library.so",
"srrg2_solver/lib/libsrrg2_solver_linear_solvers_library.so",
"srrg2_solver/lib/libsrrg2_solver_projective_library.so",
"srrg2_solver/lib/libsrrg2_solver_sparse_block_matrix_library.so",
"srrg2_solver/lib/libsrrg2_solver_types2d_library.so",
"srrg2_solver/lib/libsrrg2_solver_types3d_library.so",
"srrg2_solver/lib/libsrrg2_solver_types_common_library.so",
"srrg2_solver_extras/lib/libsrrg2_solver_extras_types2d_library.so",
"srrg2_solver_extras/lib/libsrrg2_solver_extras_types3d_library.so",
"srrg2_solver_star/lib/libsrrg2_solver_star_library.so",
"srrg2_laser_slam_2d/lib/libsrrg2_laser_slam_2d_library.so",
"srrg2_laser_slam_2d/lib/libsrrg2_laser_slam_2d_mapping_library.so",
"srrg2_laser_slam_2d/lib/libsrrg2_laser_slam_2d_sensor_processing_library.so",
"kd_slam2/lib/libkd_slam_2d_library.so",
"kd_slam2/lib/libkd_slam_3d_library.so"
           ], 
"so_paths" : [
           "/home/giorgio/workspaces/srrg2_ros2/install"
           ]
}

