"DynamicLoaderConfig" {
"so_names" : [
"srrg2_core/lib/libsrrg2_boss_library.so",
"srrg2_core/lib/libsrrg2_config_library.so",
"srrg2_core/lib/libsrrg2_configurable_shell_library.so",
"srrg2_core/lib/libsrrg2_data_structures_library.so",
"srrg2_core/lib/libsrrg2_image_library.so",
"srrg2_core/lib/libsrrg2_messages_library.so",
"srrg2_core/lib/libsrrg2_point_cloud_library.so",
"srrg2_core/lib/libsrrg2_property_library.so",
"srrg2_core/lib/libsrrg2_system_utils_library.so",
"srrg2_core/lib/libsrrg2_viewer_core_library.so",
"srrg2_core/lib/libsrrg2_viewer_library.so",
"srrg2_core_ros/lib/libsrrg2_converters_library.so",
"srrg2_core_ros/lib/libsrrg2_messages_ros_library.so",
"srrg2_qgl_viewport/lib/libsrrg2_qgl_viewport_library.so",
"srrg2_solver/lib/libsrrg2_solver_core_library.so",
"srrg2_solver/lib/libsrrg2_solver_linear_solvers_library.so",
"srrg2_solver/lib/libsrrg2_solver_sparse_block_matrix_library.so",
"srrg2_solver/lib/libsrrg2_solver_types3d_library.so",
"srrg2_solver/lib/libsrrg2_solver_types_common_library.so",
"kd_slam2/lib/libkd_slam_2d_library.so",
"kd_slam2/lib/libkd_slam_3d_library.so"
"kd_slam2/lib/libkd_slam_slam_2d_cuda.so",
"kd_slam2/lib/libkd_slam_slam_3d_cuda.so"
],
"so_paths" : [
"<KD_SLAM_ROS_WORKSPACE_INSTALL>"
]
}
