"Bundler3D" : { 
  "#id" : 1, 
  "name" : "sink", 

  // factors disabled if overlap below this
  "ba_disable_inlier_ratio" : 0.300000012, 

  // range for multiview icp [m]
  "ba_range" : 10, 

  // min fraction of inliers for cure
  "cure_min_inlier_ratio" : 0.800000012, 

  // min score for cure to consider a match
  "cure_min_score" : 30, 

  // prior for gravity info from imu
  "imu_gravity_prior_info" : 0, 

  // multiview ct-icp aligner
  "multi_cticp_aligner" : { 
    "#pointer" : 2
   }, 

  // multiview icp aligner
  "multi_icp_aligner" : { 
    "#pointer" : 3
   }, 

  // when to trigger pgo
  "pgo_chi2_threshold" : 0.100000001, 

  // PGO solver
  "solver" : { 
    "#pointer" : 4
   }, 

  // prior for velocity from cticp
  "velocity_prior_info" : 10
 }

"SolverVerboseAction" : { 
  "#id" : 5, 

  // event to which react
  "event" : 3, 

  // priority of the event, higher is 0
  "priority" : 0
 }

"SparseBlockLinearSolverCholmodFull" : { 
  "#id" : 6
 }

"ICPCUDA3D" : { 
  "#id" : 3, 
  "name" : "multi_icp", 

  // linear system damping
  "damping" : 1, 

  // chi2 kernel threshold
  "kernel_threshold" : 0.100000001, 

  // file where to dump aligner log
  "log_file" : "", 

  // max point-to-plane error
  "max_error" : 1, 

  // max ICP iterations
  "max_iterations" : 20, 

  // min inliers to accept a round
  "min_good_measurements" : 100, 

  // min cosine of normal angle
  "min_normal_cos" : 0.699999988, 

  // termination criteria
  "term_crit" : { 
    "#pointer" : -1
   }
 }

"CTICPCUDA3D" : { 
  "#id" : 2, 
  "name" : "ba_cticp", 

  // linear system damping
  "damping" : 1, 

  // chi2 kernel threshold
  "kernel_threshold" : 0.100000001, 

  // file where to dump aligner log
  "log_file" : "", 

  // max point-to-plane error
  "max_error" : 1, 

  // max ICP iterations
  "max_iterations" : 20, 

  // min inliers to accept a round
  "min_good_measurements" : 10, 

  // min cosine of normal angle
  "min_normal_cos" : 0.800000012, 

  // termination criteria
  "term_crit" : { 
    "#pointer" : -1
   }, 

  // velocity regularization weight
  "velocity_damping" : 1e+09
 }

"Solver" : { 
  "#id" : 4, 
  "actions" : [ { 
  "#pointer" : 5
 } ], 

  // pointer to the optimization algorithm (GN/LM or others)
  "algorithm" : { 
    "#pointer" : 7
   }, 

  // pointer to linear solver used to compute Hx=b
  "linear_solver" : { 
    "#pointer" : 6
   }, 
  "max_iterations" : [ 100 ], 

  // Minimum mean square error variation to perform global optimization
  "mse_threshold" : -1, 
  "robustifier_policies" : [  ], 

  // term criteria ptr, if 0 solver will do max iterations
  "termination_criteria" : { 
    "#pointer" : 8
   }, 

  // turn it off to make the world a better place
  "verbose" : 0
 }

"IterationAlgorithmLM" : { 
  "#id" : 7, 

  // max lm iterations [default: 10]
  "lm_iterations_max" : 10, 

  // upper clamp for lambda if things go well
  "step_high" : 0.666666687, 

  // lower clamp for lambda if things go well 
  "step_low" : 0.333333343, 

  // scale factor for the lambda computed by the system, do not influence the one provided by the user [default: 1e-5]
  "tau" : 9.99999975e-06, 

  // initial lm lambda, if 0 is computed by system [default: 0]
  "user_lambda_init" : 0, 

  // set to true uses lambda*diag(H), otherwise uses lambda*I [default: true]
  "variable_damping" : 1
 }

"PerturbationNormTerminationCriteria" : { 
  "#id" : 8, 

  // maximum perturbation norm
  "epsilon" : 9.99999997e-07
 }

