"BossMessageWriter" : { 
  "#id" : 1, 
  "name" : "writer", 

  // output bag path
  "out_path" : ""
 }

"Rosbag2MessageReader" : { 
  "#id" : 2, 
  "name" : "reader", 

  // input bag path
  "bag_path" : "", 
  "topics" : [ "/tf_static", "/ouster/points", "/ouster/imu" ]
 }

